### ISSUE TITLE
Need schematic to run FluidNC

### ISSUE THREAD

**Issue by holla2040** [Macrobase-tech/CNC-Software#1]
What board is this a clone of? I want to run FluidNC (updated code from here) but can't because I need schematic and/or config file.

**Comment by Macrobase-tech** [comment]
Sorry Sir,
Our supplier doesn't provide schematic so far.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Macrobase-tech/CNC-Software"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 上午8:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Macrobase-tech/CNC-Software] Need schematic to run FluidNC (Issue #1)





 
What board is this a clone of? I want to run FluidNC (updated code from here) but can't because I need schematic and/or config file.

**Comment by holla2040** [comment]
> Sorry Sir, Our supplier doesn't provide schematic so far.

You should request it. Otherwise this board is very hard to update with new software. ESP32 GRBL is very configurable, without a schematic, it takes a long time to configure it.

**Comment by Macrobase-tech** [comment]
I had checked with him,but we didn't get.




1005918473
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Macrobase-tech/CNC-Software"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sun, Feb 5, 2023 03:43 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Macrobase-tech/CNC-Software] Need schematic to run FluidNC (Issue #1)





  
Sorry Sir, Our supplier doesn't provide schematic so far.
  
You should request it. Otherwise this board is very hard to update with new software. ESP32 GRBL is very configurable, without a schematic, it takes a long time to configure it.

**Comment by holla2040** [comment]
OK, thanks for asking.
